=== VVencel2024/WEBK-NYVT-RAK_BQ5HU5/WebXMLSemTaskBQ5HU5/DomReadBQ5HU5/XMLSchemaBQ5HU5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="allatmenhely">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gondozok" type="GondozokTipus"/>
                <xs:element name="allatok" type="AllatokTipus"/>
                <xs:element name="orokbefogadok" type="OrokbefogadokTipus"/>
                <xs:element name="orvosiVizsgalatok" type="VizsgalatokTipus"/>
                <xs:element name="jelentkezesek" type="JelentkezesekTipus"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="gondozoKulcs">
            <xs:selector xpath="gondozok/gondozo"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="allatKulcs">
            <xs:selector xpath="allatok/allat"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="orokbefogadoKulcs">
            <xs:selector xpath="orokbefogadok/orokbefogado"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="vizsgalatKulcs">
            <xs:selector xpath="orvosiVizsgalatok/vizsgalat"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="jelentkezesKulcs">
            <xs:selector xpath="jelentkezesek/jelentkezes"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:keyref name="allatGondozoRef" refer="gondozoKulcs">
            <xs:selector xpath="allatok/allat"/>
            <xs:field xpath="@gondozoRef"/>
        </xs:keyref>

        <xs:keyref name="vizsgalatAllatRef" refer="allatKulcs">
            <xs:selector xpath="orvosiVizsgalatok/vizsgalat"/>
            <xs:field xpath="@allatRef"/>
        </xs:keyref>

        <xs:keyref name="jelentkezesAllatRef" refer="allatKulcs">
            <xs:selector xpath="jelentkezesek/jelentkezes"/>
            <xs:field xpath="@allatRef"/>
        </xs:keyref>

        <xs:keyref name="jelentkezesOrokbefogadoRef" refer="orokbefogadoKulcs">
            <xs:selector xpath="jelentkezesek/jelentkezes"/>
            <xs:field xpath="@orokbefogadoRef"/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="NevTipus">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LakcimTipus">
        <xs:sequence>
            <xs:element name="iranyitoszam" type="xs:string"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LeirasTipus">
        <xs:sequence>
            <xs:element name="szin" type="xs:string"/>
            <xs:element name="meret" type="xs:string"/>
            <xs:element name="ismertetoJegy" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KezelesTipus">
        <xs:sequence>
            <xs:element name="gyogyszer" type="xs:string"/>
            <xs:element name="adagolas" type="xs:string"/>
            <xs:element name="idotartam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="GondozokTipus">
        <xs:sequence>
            <xs:element name="gondozo" type="GondozoTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="GondozoTipus">
        <xs:sequence>
            <xs:element name="nev" type="NevTipus"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="telefonszamok">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="telefonszam" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="munkakor" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="AllatokTipus">
        <xs:sequence>
            <xs:element name="allat" type="AllatTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AllatTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="faj" type="xs:string"/>
            <xs:element name="fajta" type="xs:string"/>
            <xs:element name="kor" type="xs:integer"/>
            <xs:element name="leiras" type="LeirasTipus"/>
            <xs:element name="oltasok">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="oltas" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="gondozoRef" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrokbefogadokTipus">
        <xs:sequence>
            <xs:element name="orokbefogado" type="OrokbefogadoTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrokbefogadoTipus">
        <xs:sequence>
            <xs:element name="nev" type="NevTipus"/>
            <xs:element name="lakcim" type="LakcimTipus"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="korabbiAllatok">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="allatfaj" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="VizsgalatokTipus">
        <xs:sequence>
            <xs:element name="vizsgalat" type="VizsgalatTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VizsgalatTipus">
        <xs:sequence>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="tipus" type="xs:string"/>
            <xs:element name="diagnozis" type="xs:string"/>
            <xs:element name="kezeles" type="KezelesTipus"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="allatRef" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="JelentkezesekTipus">
        <xs:sequence>
            <xs:element name="jelentkezes" type="JelentkezesTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="JelentkezesTipus">
        <xs:sequence>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="motivacio" type="xs:string"/>
            <xs:element name="statusz" type="xs:string"/>
            <xs:element name="megjegyzes" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="allatRef" type="xs:IDREF" use="required"/>
        <xs:attribute name="orokbefogadoRef" type="xs:IDREF" use="required"/>
    </xs:complexType>

</xs:schema>

=== VVencel2024/WEBK-NYVT-RAK_BQ5HU5/WebXMLSemTaskBQ5HU5/DomReadBQ5HU5/XMLBQ5HU5.xml
<?xml version="1.0" encoding="UTF-8"?>
<allatmenhely xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="XMLSchemaBQ5HU5.xsd">

    <gondozok>
        <gondozo id="G1">
            <nev>
                <vezeteknev>Kovács</vezeteknev>
                <keresztnev>Anna</keresztnev>
            </nev>
            <email>kovacs.anna@menhely.hu</email>
            <telefonszamok>
                <telefonszam>+36201234567</telefonszam>
                <telefonszam>+36301234567</telefonszam>
            </telefonszamok>
            <munkakor>állatgondozó</munkakor>
        </gondozo>

        <gondozo id="G2">
            <nev>
                <vezeteknev>Nagy</vezeteknev>
                <keresztnev>Béla</keresztnev>
            </nev>
            <email>nagy.bela@menhely.hu</email>
            <telefonszamok>
                <telefonszam>+36207654321</telefonszam>
            </telefonszamok>
            <munkakor>telephelyvezető</munkakor>
        </gondozo>

        <gondozo id="G3">
            <nev>
                <vezeteknev>Szabó</vezeteknev>
                <keresztnev>Eszter</keresztnev>
            </nev>
            <email>szabo.eszter@menhely.hu</email>
            <telefonszamok>
                <telefonszam>+36305556666</telefonszam>
            </telefonszamok>
            <munkakor>önkéntes koordinátor</munkakor>
        </gondozo>
    </gondozok>

    <allatok>
        <allat id="A1" gondozoRef="G1">
            <nev>Buksi</nev>
            <faj>kutya</faj>
            <fajta>keverék</fajta>
            <kor>4</kor>
            <leiras>
                <szin>barna</szin>
                <meret>közepes</meret>
                <ismertetoJegy>fehér folt a mellkason</ismertetoJegy>
            </leiras>
            <oltasok>
                <oltas>veszettség elleni oltás</oltas>
                <oltas>kombinált oltás</oltas>
            </oltasok>
        </allat>

        <allat id="A2" gondozoRef="G1">
            <nev>Mici</nev>
            <faj>macska</faj>
            <fajta>európai rövidszőrű</fajta>
            <kor>2</kor>
            <leiras>
                <szin>szürke</szin>
                <meret>kicsi</meret>
                <ismertetoJegy>zöld szem</ismertetoJegy>
            </leiras>
            <oltasok>
                <oltas>kombinált macskaoltás</oltas>
            </oltasok>
        </allat>

        <allat id="A3" gondozoRef="G2">
            <nev>Morci</nev>
            <faj>kutya</faj>
            <fajta>németjuhász keverék</fajta>
            <kor>6</kor>
            <leiras>
                <szin>fekete-barna</szin>
                <meret>nagy</meret>
                <ismertetoJegy>féloldalt lógó fül</ismertetoJegy>
            </leiras>
            <oltasok>
                <oltas>veszettség elleni oltás</oltas>
                <oltas>chip regisztráció</oltas>
            </oltasok>
        </allat>
    </allatok>

    <orokbefogadok>
        <orokbefogado id="O1">
            <nev>
                <vezeteknev>Tóth</vezeteknev>
                <keresztnev>Péter</keresztnev>
            </nev>
            <lakcim>
                <iranyitoszam>3950</iranyitoszam>
                <varos>Sárospatak</varos>
                <utca>Rákóczi utca</utca>
                <hazszam>12</hazszam>
            </lakcim>
            <email>toth.peter@email.hu</email>
            <korabbiAllatok>
                <allatfaj>kutya</allatfaj>
                <allatfaj>macska</allatfaj>
            </korabbiAllatok>
        </orokbefogado>

        <orokbefogado id="O2">
            <nev>
                <vezeteknev>Kiss</vezeteknev>
                <keresztnev>Réka</keresztnev>
            </nev>
            <lakcim>
                <iranyitoszam>3980</iranyitoszam>
                <varos>Sátoraljaújhely</varos>
                <utca>Kossuth utca</utca>
                <hazszam>8</hazszam>
            </lakcim>
            <email>kiss.reka@email.hu</email>
            <korabbiAllatok>
                <allatfaj>macska</allatfaj>
            </korabbiAllatok>
        </orokbefogado>

        <orokbefogado id="O3">
            <nev>
                <vezeteknev>Varga</vezeteknev>
                <keresztnev>Dániel</keresztnev>
            </nev>
            <lakcim>
                <iranyitoszam>3525</iranyitoszam>
                <varos>Miskolc</varos>
                <utca>Petőfi utca</utca>
                <hazszam>3</hazszam>
            </lakcim>
            <email>varga.daniel@email.hu</email>
            <korabbiAllatok>
                <allatfaj>kutya</allatfaj>
            </korabbiAllatok>
        </orokbefogado>
    </orokbefogadok>

    <orvosiVizsgalatok>
        <vizsgalat id="V1" allatRef="A1">
            <datum>2026-02-10</datum>
            <tipus>általános vizsgálat</tipus>
            <diagnozis>egészséges</diagnozis>
            <kezeles>
                <gyogyszer>nincs</gyogyszer>
                <adagolas>nincs</adagolas>
                <idotartam>0 nap</idotartam>
            </kezeles>
        </vizsgalat>

        <vizsgalat id="V2" allatRef="A2">
            <datum>2026-03-01</datum>
            <tipus>oltás</tipus>
            <diagnozis>oltás beadva</diagnozis>
            <kezeles>
                <gyogyszer>kombinált oltóanyag</gyogyszer>
                <adagolas>1 adag</adagolas>
                <idotartam>1 nap</idotartam>
            </kezeles>
        </vizsgalat>

        <vizsgalat id="V3" allatRef="A3">
            <datum>2026-03-15</datum>
            <tipus>sérülés ellenőrzés</tipus>
            <diagnozis>enyhe lábsérülés</diagnozis>
            <kezeles>
                <gyogyszer>gyulladáscsökkentő</gyogyszer>
                <adagolas>napi 1 tabletta</adagolas>
                <idotartam>5 nap</idotartam>
            </kezeles>
        </vizsgalat>
    </orvosiVizsgalatok>

    <jelentkezesek>
        <jelentkezes id="J1" allatRef="A1" orokbefogadoRef="O1">
            <datum>2026-04-01</datum>
            <motivacio>Családi kutyát szeretnének örökbe fogadni.</motivacio>
            <statusz>elfogadva</statusz>
            <megjegyzes>Megfelelő körülmények.</megjegyzes>
        </jelentkezes>

        <jelentkezes id="J2" allatRef="A2" orokbefogadoRef="O2">
            <datum>2026-04-03</datum>
            <motivacio>Lakásban tartható macskát keres.</motivacio>
            <statusz>függőben</statusz>
            <megjegyzes>Előzetes egyeztetés folyamatban.</megjegyzes>
        </jelentkezes>

        <jelentkezes id="J3" allatRef="A1" orokbefogadoRef="O3">
            <datum>2026-04-05</datum>
            <motivacio>Korábban is tartott kutyát.</motivacio>
            <statusz>elutasítva</statusz>
            <megjegyzes>Az állat már más jelentkezőhöz került.</megjegyzes>
        </jelentkezes>
    </jelentkezesek>

</allatmenhely>
